apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fashionista
spec:
  selector:
    app: fashionista-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP