apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: fashionista
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6-jammy
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: fashionista
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db # Where MongoDB stores its data inside the Container
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc  # The actual PVC that holds the real persistent data
